channels:
- conda-forge
dependencies:
- python=3.11.8
- pip<=23.3.1
- pip:
  - mlflow==2.12.2
  - click==8.1.7
  - cloudpickle==2.2.1
  - configparser==5.0.2
  - cytoolz==0.12.2
  - defusedxml==0.7.1
  - dill==0.3.8
  - distributed==2023.11.0
  - flaml==2.3.4.post2
  - gmpy2==2.1.2
  - graphviz==0.20.1
  - importlib-metadata==7.0.1
  - jinja2==3.1.3
  - lightgbm==4.3.0
  - lz4==4.3.2
  - matplotlib==3.8.0
  - nni==3.0
  - numpy==1.26.4
  - optuna==3.6.1
  - packaging==23.1
  - pandas==2.1.4
  - pyarrow==14.0.2
  - pyjwt==2.4.0
  - pytorch-lightning==2.0.3
  - pyyaml==6.0.1
  - requests==2.31.0
  - rich==13.3.5
  - scikit-learn==1.2.2
  - scipy==1.11.4
  - synapseml-cognitive==1.0.11.dev1
  - synapseml-core==1.0.11.dev1
  - synapseml-deep-learning==1.0.11.dev1
  - synapseml-internal==1.0.11.1.dev1
  - synapseml-lightgbm==1.0.11.dev1
  - synapseml-mlflow==1.0.30.post1
  - synapseml-opencv==1.0.11.dev1
  - synapseml-vw==1.0.11.dev1
  - transformers==4.37.2
  - xgboost==2.0.3
  - xxhash==2.0.2
  - zstandard==0.19.0
name: mlflow-env
